name: Bug Report
description: Create a report to help us improve
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: describe-the-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: to-reproduce
    attributes:
      label: To reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Tell us what you expected!
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Saber version
      description: You can find this on the Settings page.
      placeholder: e.g. v0.9.11 F-Droid (9110)
    validations:
      required: true
  - type: textarea
    id: device
    attributes:
      label: Device
      description: Please complete the following information
      value: |
        - Device: [e.g. Google Pixel 6]
        - OS: [e.g. Android 13]
        - Browser (if applicable): [e.g. Firefox]
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        Screen recordings are especially useful!
    validations:
      required: false
