name: Feature Request
description: Suggest an idea for this project
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. E.g. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Saber version
      description: You can find this on the Settings page.
      placeholder: e.g. v0.9.11 F-Droid (9110)
    validations:
      required: true
  - type: textarea
    id: device
    attributes:
      label: Device
      description: Please complete the following information
      value: |
        - Device: [e.g. Google Pixel 6]
        - OS: [e.g. Android 13]
        - Browser (if applicable): [e.g. Firefox]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the feature you are suggesting!
        Screen recordings are especially useful!
    validations:
      required: false
