name: Build web nightly

on:
  # Enable manual run
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    tags:
      - '**'

env:
  project-id: com.adilhanney.saber

jobs:
  build-web-nightly:
    name: Build web nightly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Remove unneeded files
        run: |
          rm -rf android
          rm -rf appimage
          rm -rf assets_raw
          rm -rf flatpak
          rm -rf installers
          rm -rf integration_test
          rm -rf ios
          rm -rf linux
          rm -rf macos
          rm -rf metadata
          rm -rf snap
          rm -rf submodules
          rm -rf test
          rm -rf windows

      - name: Install Flutter dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libx11-dev pkg-config cmake ninja-build libblkid-dev libsecret-1-dev libjsoncpp-dev

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get

      - name: Mark build as dirty
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: cp lib/main_dirty.dart lib/main.dart

      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /saber/
