name: Build web nightly

on:
  # Enable manual run
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:

env:
  project-id: com.adilhanney.saber

jobs:
  build-web-nightly:
    name: Build web nightly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Remove unneeded files
        run: |
          rm -rf assets_raw
          rm -rf submodules

      - name: Install Flutter dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libx11-dev pkg-config cmake ninja-build libblkid-dev libsecret-1-dev libjsoncpp-dev

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get

      - name: Mark build as dirty
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          sed -i -e 's!dirty: null,!dirty: true,!g' lib/main.dart

      - name: Run tests
        id: tests
        run: flutter test --reporter expanded --coverage

      - name: Upload to Codecov
        if: success() || steps.tests.conclusion == 'failure' # run even if tests fail
        uses: codecov/codecov-action@v3
        with:
          files: coverage/lcov.info

      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /saber/
